<!DOCTYPE html>
<?php define("CURRENT_PAGE", 'overn'); ?>
<?php include("shared/language_setter.php"); ?>
<html>
  <head>
    <title><?php echo TITLE; ?></title>
    <?php include("shared/head.html"); ?>

    <style type="text/css">
      @page {  }
      table { border-collapse:collapse; border-spacing:0; empty-cells:show }
      td, th { vertical-align:top; font-size:10pt; border: 1px solid black;}
      h1, h2, h3, h4, h5, h6 { clear:both }
      ol, ul { margin:0; padding:0;}
      li { list-style: none; margin:0; padding:0;}
      <!-- "li span.odfLiEnd" - IE 7 issue-->
      li span. { clear: both; line-height:0; width:0; height:0; margin:0; padding:0; }
      span.footnodeNumber { padding-right:1em; }
      span.annotation_style_by_filter { font-size:95%; font-family:Arial; background-color:#fff000;  margin:0; border:0; padding:0;  }
      * { margin:0;}
      .ta1 { writing-mode:lr-tb; }
      .ta2 { writing-mode:lr-tb; }
      .ta3 { writing-mode:lr-tb; }
      .Default { font-family:Calibri; background-color:transparent; border-style:none; vertical-align:bottom; margin-left:0cm; writing-mode:page; color:#000000; font-size:11pt; font-style:normal; text-shadow:none; text-decoration:none ! important; font-weight:normal; }
      .ce1 { background-color:#e6b9b8; border-width:0,0349cm; border-style:solid; border-color:#000000; color:#000000; font-size:16pt; font-style:normal; font-weight:bold; margin-left:0cm; text-shadow:none; font-family:Calibri; text-decoration:none ! important; vertical-align:bottom; writing-mode:page; }
      .ce2 { background-color:#8eb4e3; border-width:0,0349cm; border-style:solid; border-color:#000000; color:#000000; font-size:11pt; font-style:normal; font-weight:bold; margin-left:0cm; text-shadow:none; font-family:Calibri; text-decoration:none ! important; vertical-align:bottom; writing-mode:page; }
      .ce3 { background-color:transparent; border-width:0,0349cm; border-style:solid; border-color:#000000; color:#000000; font-size:11pt; font-style:normal; font-weight:normal; margin-left:0cm; text-shadow:none; font-family:Calibri; text-decoration:none ! important; vertical-align:bottom; writing-mode:page; }
      .ce4 { background-color:#ffffff; border-width:0,0349cm; border-style:solid; border-color:#000000; color:#000000; font-size:11pt; font-style:normal; font-weight:bold; margin-left:0cm; text-shadow:none; font-family:Calibri; text-decoration:none ! important; vertical-align:bottom; writing-mode:page; }
      .ce5 { background-color:transparent; border-style:none; color:#000000; font-size:16pt; font-style:normal; font-weight:bold; margin-left:0cm; text-shadow:none; font-family:Calibri; text-decoration:none ! important; vertical-align:bottom; writing-mode:page; }
      .ce6 { background-color:#d99694; border-width:0,0349cm; border-style:solid; border-color:#000000; color:#000000; font-size:16pt; font-style:normal; font-weight:bold; margin-left:0cm; text-shadow:none; font-family:Calibri; text-decoration:none ! important; vertical-align:bottom; writing-mode:page; }
      .ce7 { background-color:#ffffff; border-width:0,0349cm; border-style:solid; border-color:#000000; color:#000000; font-size:11pt; font-style:normal; font-weight:normal; margin-left:0cm; text-shadow:none; font-family:Calibri; text-decoration:none ! important; vertical-align:bottom; writing-mode:page; }
      .ce8 { background-color:#ffffff; border-style:none; color:#000000; font-size:11pt; font-style:normal; font-weight:normal; margin-left:0cm; text-shadow:none; font-family:Calibri; text-decoration:none ! important; vertical-align:bottom; writing-mode:page; }
      .co1 { width:6.81cm; }
      .co2 { width:10.62cm; }
      .co3 { width:5.75cm; }
      .co4 { width:2.602cm; }
      .ro1 { height:0.741cm; }
      .ro2 { height:0.529cm; }
      <!-- ODF styles with no properties representable as CSS -->
      { }
    </style>

  </head>
  <body class="index">

    <?php include("shared/header.php"); ?>
    <?php include("shared/navigation.php"); ?>
    <div class="main">
      <div class="whiteback">

        <article id="content" class="<?php echo CURRENT_PAGE; ?>">
          <div class="wrapper">
            <div class="pad">



              <table border="0" cellspacing="0" cellpadding="0" class="ta1"><colgroup><col width="298"/><col width="464"/><col width="251"/><col width="114"/></colgroup>
                <tr class="ro1"><td style="text-align:left;width:6.81cm; " class="Default"> </td><td style="text-align:left;width:10.62cm; " class="ce5"><p>Detaljert oversikt overnatting</p></td><td style="text-align:left;width:5.75cm; " class="Default"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro1"><td style="text-align:left;width:6.81cm; " class="ce1"><p>STED</p></td><td style="text-align:left;width:10.62cm; " class="ce6"><p>HVEM</p></td><td style="text-align:left;width:5.75cm; " class="ce6"><p>Nøkler</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>

                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Kjell Eide Hytte</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Axel og Inga + Nicolai</p></td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Pappa Jan</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Kjell Ivars Sjøhus</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Pappa Jan</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 1 </p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Erling og Sanne</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 2</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Sannes Foreldre</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Karin og Jan (Kaiveien 18)</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 1 </p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Karin og Jan</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 2</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Julie og Eigil</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 3</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Irma</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Åge's Sjøhus</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 1</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Liven og Bill</p></td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Pappa Jan</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 2</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Bestemamma</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 3</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Dikke</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Anita's Sjøhus</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 1 </p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Kine og Magnus</p></td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Pappa Jan</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 2</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Nina og Amalie</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 3</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Amalie (barnevakt) + kjæresten</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Gerd's Sjøhus</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 1 </p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Silje og Nico</p></td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Pappa Jan</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 2</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Rasmus og Anne</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 3</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Therese og Kristoffer</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Bryggehus 1</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 1 </p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Lars- Ola, Tore, </p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 2</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Kim, Frode</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 3</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Arne, Hjalmar</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Bryggehus 2</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 1 </p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Øyvind og Margrete</p></td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 2</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Geir og Stine</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 3</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Sigurd og Ellen</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Bryggehus 3</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>BANDET</p></td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce4"> </td><td style="text-align:left;width:10.62cm; " class="ce7"> </td><td style="text-align:left;width:5.75cm; " class="ce7"> </td><td style="text-align:left;width:2.602cm; " class="ce8"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Bryggehus 6</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 1 </p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Magnus og Linda</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 2</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Geir og Betina</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 3</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Christina og Øystein</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Bryggehus 7</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 1 </p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Jon og Elaine </p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 2</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Kay Rune og Solveig</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 3</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Nina</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Bryggehus 8</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 1 </p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Nate og Sarah</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 2</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Imran</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 3</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Fahad </p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Bryggehus 9</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 1 </p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Nicolai og Anne Marie</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 2</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Nicolai jr</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 3</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Willy</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Hotellrom 1</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom nede</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Fredrikke + Fanny</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom oppe</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Venninne av Fredrikke</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Hotellrom 2</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom nede</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Kent</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom oppe</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Lea</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Hotellrom 3</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom nede</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Rita og Kai</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom oppe</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Hotellrom 4</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>farmor Ada og farfar Gunnar Gabrielsen</p></td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom nede</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom oppe</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Hotellrom 5</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom nede</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Aud og Peder Lunde</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom oppe</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Hotellrom 6</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom nede</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Elisabeth</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom oppe</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Hotellrom 7</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom nede</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Gerd og Hans</p></td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom oppe</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Hotellrom 8</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom nede</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Åse og Tor Olav</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom oppe</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="Default"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Hotellrom 9</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Lillian</p></td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Resepsjonen</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"> </td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce2"><p>Prestegården (hovedhus)</p></td><td style="text-align:left;width:10.62cm; " class="ce3"> </td><td style="text-align:left;width:5.75cm; " class="ce3"><p>Pappa Jan/evt hverandre</p></td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 1 (4p)</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Maja, Anette, Kirsten, Mailinn</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 2 (6p)</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Edward, Torbjørn, Trond, Tormod, Oscar, Endre</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 3 (6p)</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Charlotte, Monika,  Marianne S, Susanne</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="ce3"><p>Rom 4 (6p)</p></td><td style="text-align:left;width:10.62cm; " class="ce3"><p>Karoline, Gunhild, Tiffanie, Rabab, Marianne H</p></td><td style="text-align:left;width:5.75cm; " class="ce3"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="Default"> </td><td style="text-align:left;width:10.62cm; " class="Default"> </td><td style="text-align:left;width:5.75cm; " class="Default"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:6.81cm; " class="Default"> </td><td style="text-align:left;width:10.62cm; " class="Default"> </td><td style="text-align:left;width:5.75cm; " class="Default"> </td><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
              </table>
              <table border="0" cellspacing="0" cellpadding="0" class="ta2">
                <colgroup><col width="114"/></colgroup>

                <tr class="ro2"><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>

                <tr class="ro2"><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr></table><table border="0" cellspacing="0" cellpadding="0" class="ta3"><colgroup><col width="114"/></colgroup>
                <tr class="ro2"><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
                <tr class="ro2"><td style="text-align:left;width:2.602cm; " class="Default"> </td></tr>
              </table>


            </div>
          </div>
        </article>

      </div>
    </div>

  </body>
</html>


